objects/Costing__c.object
<CustomObject>
    <fields>
        <fullName>Architect__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Architect</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Construct__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Construct</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deploy__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Deploy</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consultant_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Costing__c</fullName>
        <label>Project Costing</label>
        <referenceTo>Project_Costing__c</referenceTo>
        <relationshipLabel>Costings</relationshipLabel>
        <relationshipName>Costings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sales Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Support</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Validate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Validate</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Costing</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Costings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Costing__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Costings</relationshipLabel>
        <relationshipName>Project_Costings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Costing</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Costings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Consultant_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Consultant Level</masterLabel>
</GlobalValueSet>

classes/relatedListWithSyncCtrlTest.cls
@isTest
public class relatedListWithSyncCtrlTest {
    /*public Opportunity opp;
public Project_Costing__c pc;
public Costing__c costing;*/
    
    @testSetup
    static void setup() {
        Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        Opportunity opp2 = new Opportunity(Name = 'test 2', StageName = 'Specification', CloseDate = System.today());
        insert opp;
        insert opp2;
        Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Project_Costing__c pc2 = new Project_Costing__c(Name='Sample Project Two',Opportunity__c=opp2 .id,CurrencyIsoCode='SGD');
        insert pc;
        insert pc2;
        Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        insert dummyCosting;
    }
    
    @isTest static void testDelete() {
        test.startTest();
        //Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        //Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Project_Costing__c dummyCosting = [SELECT id FROM Project_Costing__c LIMIT 1];      
        //new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        relatedListWithSyncCtrl.deleteAccount(dummyCosting.ID);
        test.stopTest();
        //System.assertEquals(0,celsius);
    }
    
    
     @isTest static void testsync() {
        test.startTest();
        //Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        //Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Project_Costing__c dummyCosting = [SELECT id FROM Project_Costing__c LIMIT 1];      
        //new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        relatedListWithSyncCtrl.syncTwo(dummyCosting.ID);
        test.stopTest();
        //System.assertEquals(0,celsius);
    }
    
    @isTest static void testFetchRecordOppty() {
        test.startTest();
        //Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        //Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        //Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        Opportunity dummyCosting = [SELECT id FROM Opportunity LIMIT 1];      
        
        system.debug(dummyCosting.Id);
        relatedListWithSyncCtrl.fetchRecordCountOppty(dummyCosting.Id);
        
        //System.assertEquals(0,celsius);
    }
    
    @isTest static void testFetchRecord() {
        test.startTest();
        //Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        //Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        //Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        
        Opportunity dummyCosting = [SELECT id FROM Opportunity LIMIT 1];      
        
        system.debug(dummyCosting.Id);
        relatedListWithSyncCtrl.fetchRecordCount(dummyCosting.Id);
        
        //System.assertEquals(0,celsius);
    }
    
    
    
    @isTest static void testFetch() {
        test.startTest();
        //Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        //Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        //Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id, Sales_Rate__c=45, Architect__c=45, Construct__c=45, Validate__c=45, Deploy__c=45, Support__c=45);
        Project_Costing__c dummyCosting = [SELECT id FROM Project_Costing__c LIMIT 1];      
        
        system.debug(dummyCosting.Id);
        relatedListWithSyncCtrl.fetchDetails(dummyCosting.Id);
        
        //System.assertEquals(0,celsius);
    }
    
    @isTest static void testSave() {
        test.startTest();
        Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id);
        
        List < Project_Costing__c > returnDetailList = new List < Project_Costing__c > ();
        
        
        relatedListWithSyncCtrl.saveAccount(returnDetailList);
        
        //System.assertEquals(0,celsius);
    }
    
    
    @isTest static void testGetselectOptions() {
        test.startTest();
        Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id);
        
        
        
        
        relatedListWithSyncCtrl.getselectOptions(dummyCosting,'Level__c');
        
        
    }
    
    @isTest static void testSaveContacts() {
        test.startTest();
        Opportunity opp = new Opportunity(Name = 'test', StageName = 'Specification', CloseDate = System.today());
        Project_Costing__c pc = new Project_Costing__c(Name='Sample Project',Opportunity__c=opp.id,CurrencyIsoCode='SGD');
        Costing__c dummyCosting = new Costing__c(Name='Sample Costing',Level__c='Consultant',Project_Costing__c=pc.id);
        
        List < Project_Costing__c > returnDetailList = new List < Project_Costing__c > ();
        
        
        relatedListWithSyncCtrl.saveContacts(returnDetailList);
        
        //System.assertEquals(0,celsius);
    }
    
    
    /*'sobjectType': 'Costing__c',
'Name': '',
'Level__c': '',
'Sales_Rate__c': '',
'Architect__c': '',
'Construct__c': '',
'Validate__c': '',
'Deploy__c': '',
'Support__c': '',
"Project_Costing__c": component.get("v.recordId")*/
    
}