objects/Costing__c.object
<CustomObject>
    <fields>
        <fullName>Architect__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Architect</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Construct__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Construct</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <formula>CASE(
TEXT(Level__c) ,
&apos;Consultant&apos;, 29,
&apos;Senior Consultant&apos;, 46,
&apos;Architect&apos;, 63,
&apos;Principal&apos;, 88,
&apos;Partner&apos;, 124,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deploy__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Deploy</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Consultant_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Costing__c</fullName>
        <label>Project Costing</label>
        <referenceTo>Project_Costing__c</referenceTo>
        <relationshipLabel>Costings</relationshipLabel>
        <relationshipName>Costings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Price_45__c</fullName>
        <formula>Cost__c /0.55</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reference Price (45%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sales Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Support__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Support</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Days__c</fullName>
        <formula>Architect__c +  Construct__c + Validate__c + Deploy__c + Support__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>Total_Days__c * 8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Sales_Price__c</fullName>
        <formula>IF(Sales_Rate__c  * Total_Hours__c = NULL, 0, Sales_Rate__c  * Total_Hours__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Sales Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Validate</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Costing</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Costings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Costing__c.object
<CustomObject>
    <fields>
        <fullName>No_of_records__c</fullName>
        <label>No. of records</label>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Days__c</fullName>
        <label>Total Days</label>
        <summarizedField>Costing__c.Total_Days__c</summarizedField>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <summarizedField>Costing__c.Total_Hours__c</summarizedField>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project Costing</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Costings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Consultant_Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Principal</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <masterLabel>Consultant Level</masterLabel>
</GlobalValueSet>

classes/inlineEditCtrl.cls
/* sfdcmonkey.com || Date 12/07/2017 || API Version 41.0 */
public with sharing class inlineEditCtrl {
    
    /*// method for fetch account records list  
    @AuraEnabled
    public static List < account > fetchAccount() {
        
        List < Account > returnList = new List < Account > ();
        List < Account > lstOfAccount = [select id, Name, Rating, website from account LIMIT 10];
        
        
        for (Account acc: lstOfAccount) {
            returnList.add(acc);
        }
        return returnList;
    }
    
    // method for update records after inline editing  
    @AuraEnabled
    public static List < account > saveAccountt(List<Account> lstAccount) {
        update lstAccount;
        return lstAccount;
    }*/
    
    @AuraEnabled
    public static void deleteAccount(ID rowDeleted) {
        
        Costing__c[] contactsDel = [SELECT Id FROM Costing__c WHERE Id=:rowDeleted]; 

        delete contactsDel;
        
    }
    
    @AuraEnabled
    public static Decimal fetchRecordCount(Id pc) {
        Decimal recordCount = [select No_of_records__c from Project_Costing__c WHERE Id = :pc].No_of_records__c;
        return recordCount;
    }
    
    
    
   /* @AuraEnabled
    public static Costing__c deleteExpense(Costing__c rec) {
        // Perform isDeletable() check here 
        delete rec;
        return rec;
    } */ 
    
    //-	-	-	-		-	-	-		-	-	-	-	-		-	-	-		-	-	-		-	-
    //
    @AuraEnabled
    public static List < Costing__c > fetchDetails(Id pc) {
        System.debug('commenttt' + pc);
        List < Costing__c > returnDetailList = new List < Costing__c > ();
        List < Costing__c > lstOfDetails = [select Name, Level__c, Cost__c, Sales_Rate__c, Reference_Price_45__c, Architect__c, Construct__c, Validate__c, Deploy__c, Support__c, Total_Days__c, Total_Hours__c, Total_Sales_Price__c,CreatedDate from Costing__c WHERE Project_Costing__c = :pc ORDER BY CreatedDate LIMIT 100];
        
        
        for (Costing__c dtl: lstOfDetails) {
            returnDetailList.add(dtl);
        }
        

        return returnDetailList;
        
        
    }
    
    // method for update records after inline editing  
    @AuraEnabled
    public static List < Costing__c > saveAccount(List<Costing__c> lstOfDetails) {
        update lstOfDetails;
        return lstOfDetails;
    }
    // method for fetch picklist values dynamic  
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        //allOpts.sort();
        return allOpts;
    }
    
    @AuraEnabled
    public static void saveContacts(List<Costing__c> ListContact){
        Insert ListContact;
    }
}