objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>No_of_records__c</fullName>
        <label>No. of records</label>
        <summaryForeignKey>Project_Costing__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project_Costing__c.object
<CustomObject>
    <fields>
        <fullName>Blended_Sales_Rate_Per_Day__c</fullName>
        <formula>Net_Sales_Price__c /  Total_Days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Blended Sales Rate Per Day</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Cost_Price__c</fullName>
        <label>Net Cost Price</label>
        <summarizedField>Costing__c.Total_Cost_Price__c</summarizedField>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Net_Sales_Price__c</fullName>
        <label>Net Sales Price</label>
        <summarizedField>Costing__c.Total_Sales_Price__c</summarizedField>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>No_of_records__c</fullName>
        <label>No. of records</label>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Project Costings</relationshipLabel>
        <relationshipName>Project_Costings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <summarizedField>Costing__c.Total_Hours__c</summarizedField>
        <summaryForeignKey>Costing__c.Project_Costing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Margin__c</fullName>
        <formula>( Total_Sales_Rate__c - Total_Cost_Price__c )/ Total_Sales_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Project Costing</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Costings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/relatedListWithSyncCtrl.cls
public with sharing class relatedListWithSyncCtrl {
    
    @AuraEnabled
    public static void deleteAccount(ID rowDeleted) {
        
        Project_Costing__c[] contactsDel = [SELECT Id FROM Project_Costing__c WHERE Id=:rowDeleted]; 
        
        
        delete contactsDel;
        
    }
    
    /*@AuraEnabled
    public static void syncRecord(ID rowDeleted) {
        
        List<Project_Costing__c> newAccnts= new List<Project_Costing__c>();
        List<Project_Costing__c> accnts=[SELECT Id FROM Project_Costing__c WHERE Id=:rowDeleted];
        
        for(Project_Costing__c acc:accnts)
        {
                   acc.Selected_Default__c =true;

        }
        
        Update newAccnts;
        
        
        Project_Costing__c contactsDel = [SELECT Id FROM Project_Costing__c WHERE Id=:rowDeleted]; 
        contactsDel.Selected_Default__c =true;
        update contactsDel;
        
    }*/
    
    @AuraEnabled
    public static List <Project_Costing__c > syncTwo(Id rowtosync) {

        List < Project_Costing__c > returnDetailList = new List < Project_Costing__c > ();
        List < Project_Costing__c > lstOfDetails = [select Name,Net_Sales_Price__c,Net_Cost_Price__c, Total_Hours__c, Blended_Sales_Rate_Per_Day__c, CurrencyIsoCode,Total_Margin__c,No_of_records__c,Selected_Default__c  from Project_Costing__c WHERE Id = :rowtosync];
		List < Project_Costing__c > notSelected = [select Name,Net_Sales_Price__c,Net_Cost_Price__c, Total_Hours__c, Blended_Sales_Rate_Per_Day__c, CurrencyIsoCode,Total_Margin__c,No_of_records__c,Selected_Default__c  from Project_Costing__c WHERE Id != :rowtosync];

        for (Project_Costing__c dtl: lstOfDetails) {
            dtl.Selected_Default__c=true;
        }
        
        for (Project_Costing__c dtl: notSelected) {
            dtl.Selected_Default__c=false;      
        }
        
        update lstOfDetails;
        update notSelected;
        return lstOfDetails;

        //update lstOfDetails;
        //return lstOfDetails;
    }

    /*@AuraEnabled
    public static List <Project_Costing__c > syncOne(List<Project_Costing__c> lstOfDetails) {
        //update lstOfDetails;
        return lstOfDetails;
    }*/
    
    @AuraEnabled
    public static Decimal fetchRecordCountOppty(Id pc) {
        Decimal recordCount = [select No_of_records__c from Opportunity WHERE Id = :pc].No_of_records__c;
        return recordCount;
    }
    
    @AuraEnabled
     public static Decimal fetchRecordCount(Id pc) {
         Decimal recordCount = [select No_of_records__c from Project_Costing__c WHERE Opportunity__c = :pc].No_of_records__c;
         return recordCount;
     }
    
    @AuraEnabled
    public static List < Project_Costing__c > fetchDetails(Id pc) {
        System.debug('commenttt' + pc);
        List < Project_Costing__c > returnDetailList = new List < Project_Costing__c > ();
        List < Project_Costing__c > lstOfDetails = [select Name,Net_Sales_Price__c,Net_Cost_Price__c, Total_Hours__c, Blended_Sales_Rate_Per_Day__c, CurrencyIsoCode,Total_Margin__c,No_of_records__c,Selected_Default__c  from Project_Costing__c WHERE Opportunity__c = :pc ORDER BY CreatedDate LIMIT 100];
        
        
        for (Project_Costing__c dtl: lstOfDetails) {
            returnDetailList.add(dtl);
        }
        
        
        return returnDetailList;
        
        
    }
    
    // method for update records after inline editing  
    @AuraEnabled
    public static List <Project_Costing__c > saveAccount(List<Project_Costing__c> lstOfDetails) {
        update lstOfDetails;
        return lstOfDetails;
    }
    // method for fetch picklist values dynamic  
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
    
    @AuraEnabled
    public static void saveContacts(List<Project_Costing__c> ListContact){
        Insert ListContact;
    }
    
    
    
}